using Robust.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Numerics;

namespace Content.Client.Vanilla.UserInterface.GhostBackground.window;

[GenerateTypedNameReferences]
public sealed partial class GhostBackgroundWindow : DefaultWindow
{
    public GhostBackgroundWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.Visible = false;
        CloseButton.Disabled = true;
    }
    public override void Close()
    {
        // Пустой метод - окно нельзя закрыть стандартными способами
    }

    public void ForceClose()
    {
        base.Close(); // Закрытие только через этот метод
    }
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }
}
