using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? GhostGoLobbyPressed; // Corvax-GoLobby
    public event Action? TDMArenaButtonPressed;//RAYTEN
    public event Action? TTTArenaButtonPressed;//RAYTEN
    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        TDMArenaButton.OnPressed += _ => TDMArenaButtonPressed?.Invoke();//RAYTEN
        TTTArenaButton.OnPressed += _ => TTTArenaButtonPressed?.Invoke();//RAYTEN
        GhostGoLobbyButton.OnPressed += _ => GhostGoLobbyPressed?.Invoke(); // Corvax-GoLobby

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, bool? canGoLobby = true) // Corvax-GoLobby edit
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        GhostGoLobbyButton.Visible = canGoLobby ?? true; // Corvax-GoLobby

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    // RAYTEN STARTS
    public void TDMUpdate(TimeSpan timeToNewCycle, int tdmwannajoin)
    {
        if (timeToNewCycle <= TimeSpan.FromSeconds(-1))
        {
            TDMArenaButton.Text = Loc.GetString("TDM-NotAvailable");
            TDMArenaButton.Disabled = true;
        }
        else
        {
            var blueguys = (tdmwannajoin % 2 == 1) ? tdmwannajoin / 2 + 1 : tdmwannajoin / 2;
            var redguys = tdmwannajoin / 2;
            TDMArenaButton.Text = Loc.GetString("TDM-Available", ("blueguys", blueguys), ("redguys", redguys), ("timer", timeToNewCycle));
            TDMArenaButton.Disabled = false;
        }
    }
    public void TTTUpdate(TimeSpan timeToNewCycle, int tTTwannajoin)
    {
        if (timeToNewCycle <= TimeSpan.FromSeconds(-1))
        {
            TTTArenaButton.Text = Loc.GetString("TTT-NotAvailable");
            TTTArenaButton.Disabled = true;
        }
        else
        {
            TTTArenaButton.Text = Loc.GetString("TTT-Available", ("players", tTTwannajoin), ("timer", timeToNewCycle));
            TTTArenaButton.Disabled = false;
        }
    }
    // RAYTEN ENDS

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
