using Robust.Shared.Utility;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Vanilla.UserInterface.BrainWorm.Chemicals.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChemicalControl : Control
{
    public event Action? OnPressed;
    public ChemicalControl(string name, string desc, Color color)
    {
        RobustXamlLoader.Load(this);

        var nameMessage = new FormattedMessage();
        nameMessage.AddMarkupOrThrow(name);

        var descMessage = new FormattedMessage();
        descMessage.AddMarkupOrThrow(desc);

        ChemicalNameLabel.SetMessage(nameMessage);
        ChemicalDescLabel.SetMessage(descMessage);

        ChemicalButton.OnPressed += _ => OnPressed?.Invoke();
        Background.ModulateSelfOverride = color;
    }
}

