using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Vanilla.Games.TTT.UI;

[GenerateTypedNameReferences]
public sealed partial class TTTBodyExamineMenu : FancyWindow
{
    public TTTBodyExamineMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
