using Content.Shared.Vanilla.Games.TTT.Items.Radar;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Vanilla.Games.TTT.Items.Radar;

[GenerateTypedNameReferences]
public sealed partial class TTTRadarWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IEntityManager _ent = default!;
    private TimeSpan _next = TimeSpan.Zero;
    private TimeSpan _previous = TimeSpan.Zero;
    public TTTRadarWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var next = _next - _timing.CurTime;
        var prev = _timing.CurTime - _previous;
        NextScan.Text = $"{Math.Max(0, next.TotalSeconds):F0}с.";
        PreviousScan.Text = $"{Math.Max(0, prev.TotalSeconds):F0}с. назад";
    }
    public void Set(EntityUid? mapUid, List<RadarBlip> trackedEntities, TimeSpan nextScan, TimeSpan previousScan)
    {
        NavMapScreen.MapUid = mapUid;

        NavMapScreen.TrackedCoordinates.Clear();

        foreach (var ent in trackedEntities)
            NavMapScreen.TrackedCoordinates.Add(_ent.GetCoordinates(ent.Coords), (true, ent.Color));

        NavMapScreen.ForceNavMapUpdate();

        _next = nextScan;
        _previous = previousScan;
    }
    public void Set(List<RadarBlip> trackedEntities, TimeSpan nextScan, TimeSpan previousScan)
    {
        NavMapScreen.TrackedCoordinates.Clear();
        foreach (var ent in trackedEntities)
            NavMapScreen.TrackedCoordinates.Add(_ent.GetCoordinates(ent.Coords), (true, ent.Color));
        NavMapScreen.ForceNavMapUpdate();
        _next = nextScan;
        _previous = previousScan;
    }
}
