using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.Vanilla.UserInterface.LawControls;

[GenerateTypedNameReferences]
public sealed partial class LawControl : Control
{
    public Action? OnPressed;

    public LawControl(LocId Name, bool Selectable, LocId? Desc = null)
    {
        RobustXamlLoader.Load(this);
        var LawNameMessage = new FormattedMessage();
        LawNameMessage.AddMarkupOrThrow(Loc.GetString(Name));
        LawName.SetMessage(LawNameMessage);

        MainButton.OnPressed += _ => OnPressed?.Invoke();
        MainButton.Disabled = !Selectable;

        if (Desc != null)
        {
            var tooltip = new Tooltip();
            var tooltipMessage = new FormattedMessage();
            tooltipMessage.AddMarkupOrThrow(Loc.GetString(Desc));

            tooltip.SetMessage(tooltipMessage);
            MainButton.TooltipSupplier = _ => tooltip;
        }
    }
}
