using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Vanilla.Evacuation.BUIStates;
using Content.Shared.Vanilla.Evacuation.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Vanilla.Evacuation.UI;

[GenerateTypedNameReferences]
public sealed partial class EvacuationConsoleWindow : FancyWindow,
    IComputerWindow<EvacuationConsoleBoundUserInterfaceState>
{
    public EvacuationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        EvacuateButton.OnPressed += args =>
        {
            OnEvacuatePressed(cb, args);
        };
    }

    private void OnEvacuatePressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EvacuationRequestMessage());
    }
}
