using Content.Shared.Vanilla.Competitive;
using Content.Shared.Containers.ItemSlots;
using Content.Client.Stylesheets;
using Robust.Shared.Utility;
using Robust.Shared.Audio;
using Robust.Shared.Player;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.ResourceManagement;
using System.Linq;
using System.Numerics;
namespace Content.Client.Vanilla.TechAnalysis;

[GenerateTypedNameReferences]
public sealed partial class TechnicalAnalysisMenu : BaseWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IResourceCache _cache = default!;
    private readonly AudioSystem _audio;
    private readonly ItemSlotsSystem _slots;
    public event Action<List<char>>? OnSubmitPressed;
    public event Action? OnServerSelectionButtonPressed;
    private bool _forceDisableSubmitBtn = false;
    private HashSet<char> _wrongCodons = [];
    public TechnicalAnalysisMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _slots = _entityManager.System<ItemSlotsSystem>();
        _audio = _entityManager.System<AudioSystem>();

        CloseButton.OnPressed += _ => Close();
        SubmitButton.OnPressed += _ =>
        {
            var guess = GetSubmittedGenome();
            SubmitButton.Disabled = true;
            OnSubmitPressed?.Invoke(guess);
        };

        ServerButton.OnPressed += _ => OnServerSelectionButtonPressed?.Invoke();
        ResetButton.OnPressed += _ => ResetGenomeButtons();
        var bigFont = _cache.NotoStack(size: 14);

        SubmitButton.Label.FontOverride = bigFont;
        ResetButton.Label.FontOverride = bigFont;
        ServerButton.Label.FontOverride = bigFont;
        SubmitButton.Label.AddStyleClass("ConsoleText");
        ResetButton.Label.AddStyleClass("ConsoleText");
        ServerButton.Label.AddStyleClass("ConsoleText");
    }
    public void NoItem(bool noitem)
    {
        HistoryContainer.Visible = !noitem;
        GenomeGrid.Visible = !noitem;
        NoItemLabel.Visible = noitem;
        AttemptsLeftLabel.Visible = !noitem;
    }

    public void Update(List<List<CodonFeedBack>> history, int attemptscount)
    {
        CreateGenomeInputControls(6);
        UpdateHistory(history);
        UpdateWinCondition(attemptscount);
        UpdateSubmitButtonState();
    }

    public void UpdateHistory(List<List<CodonFeedBack>> history)
    {
        HistoryContainer.RemoveAllChildren();

        foreach (var attempt in history)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
            };

            foreach (var feedback in attempt)
            {
                var button = new Button
                {
                    Text = feedback.Codon.ToString(),
                    StyleClasses = { "OpenBoth" },
                    MinWidth = 55,
                    MinHeight = 55,
                    Disabled = true,
                };
                button.Label.AddStyleClass("ConsoleText");
                switch (feedback.Hint)
                {
                    case CodonHint.Correct:
                        button.Modulate = Color.FromHex("#4CAF50"); // зеленый
                        break;
                    case CodonHint.WrongPosition:
                        button.Modulate = Color.FromHex("#FFC107"); // желтый
                        break;
                    case CodonHint.Incorrect:
                        button.Modulate = Color.FromHex("#F44336"); // красный
                        break;
                }

                row.AddChild(button);
            }

            HistoryContainer.AddChild(row);
        }
        UpdateGenomeInputFromHistory(history);
    }
    public void UpdateWinCondition(int attemptcount)
    {
        AttemptsLeftLabel.Text = Loc.GetString("TechnicalAnalysis-ui-attempts", ("count", attemptcount));

        //проиграли
        if (attemptcount <= 0)
        {
            _forceDisableSubmitBtn = true;
            return;
        }
        //играем
        _forceDisableSubmitBtn = false;

    }

    public void CreateGenomeInputControls(int buttoncount)
    {
        GenomeGrid.RemoveAllChildren();

        for (int i = 0; i < buttoncount; i++)
        {
            var button = new Button
            {
                Text = "?",
                StyleClasses = { "OpenBoth" },
                MinWidth = 50,
                MinHeight = 50,
            };
            button.Label.AddStyleClass("ConsoleText");
            int index = i;
            button.OnPressed += _ => CycleLetter(button, index);

            GenomeGrid.AddChild(button);
        }
    }
    private void CycleLetter(Button button, int index)
    {
        var letters = new[] { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K' };

        var filteredLetters = letters
            .Where(l => !_wrongCodons.Contains(l))
            .ToArray();

        if (filteredLetters.Length == 0)
        {
            button.Text = "?";
            UpdateSubmitButtonState();
            return;
        }

        var usedLetters = GenomeGrid.Children
            .OfType<Button>()
            .Select((b, i) => (Button: b, Index: i))
            .Where(x => x.Index != index && x.Button.Text is { Length: 1 })
            .Select(x => x.Button.Text![0])
            .ToHashSet();

        var currentText = button.Text;
        char current = (currentText is { Length: 1 }) ? currentText[0] : '\0';

        int idx = Array.IndexOf(filteredLetters, current);

        for (int i = 0; i < filteredLetters.Length; i++)
        {
            idx = (idx + 1) % filteredLetters.Length;
            var next = filteredLetters[idx];

            if (!usedLetters.Contains(next))
            {
                button.Text = next.ToString();

                SoundSpecifier keySound = new SoundCollectionSpecifier("Keyboard");
                _audio.PlayGlobal(keySound, Filter.Local(), false);

                UpdateSubmitButtonState();
                return;
            }
        }

        // Если все допустимые буквы уже заняты
        button.Text = "?";
        UpdateSubmitButtonState();
    }

    public List<char> GetSubmittedGenome()
    {
        var result = new List<char>();
        foreach (var child in GenomeGrid.Children)
        {
            if (child is Button btn && btn.Text != null && btn.Text.Length == 1)
            {
                result.Add(btn.Text[0]);
            }
        }
        return result;
    }

    private void UpdateGenomeInputFromHistory(List<List<CodonFeedBack>> history)
    {
        if (history.Count == 0)
            return;

        var lastAttempt = history[^1]; // Последняя попытка

        int buttonCount = GenomeGrid.Children.Count();
        var codonCount = lastAttempt.Count;
        var count = Math.Min(6, Math.Min(buttonCount, codonCount));

        for (int i = 0; i < count; i++)
        {
            if (GenomeGrid.Children.ElementAt(i) is not Button button)
                continue;

            var feedback = lastAttempt[i];

            if (feedback.Hint == CodonHint.Correct)
            {
                button.Modulate = Color.FromHex("#4CAF50"); // зелёный
                button.Text = feedback.Codon.ToString();
                button.Disabled = true;
            }
            else
            {
                button.Disabled = false;
            }
        }
        var wrongCodons = new HashSet<char>();
        foreach (var attempt in history)
        {
            foreach (var feedback in attempt)
            {
                if (feedback.Hint == CodonHint.Incorrect)
                    wrongCodons.Add(feedback.Codon);
            }
        }
        _wrongCodons = wrongCodons;
    }

    private void ResetGenomeButtons()
    {
        foreach (var child in GenomeGrid.Children)
        {
            if (child is Button button)
            {
                if (!button.Disabled)
                    button.Text = "?";
            }
        }
    }

    private void UpdateSubmitButtonState()
    {
        if (_forceDisableSubmitBtn)
            SubmitButton.Disabled = true;

        var isValid = GenomeGrid.Children
            .OfType<Button>()
            .All(b => b.Text is { Length: 1 } && b.Text != "?");

        SubmitButton.Disabled = !isValid;
    }
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
