- type: antag
  id: Diversionist
  name: roles-antag-diversionist-name
  antagonist: true
  setPreference: true
  objective: roles-antag-diversionist-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 360000

- type: antagSpecifier
  parent: BaseTraitor
  id: Diversionist
  prefRoles:
  - Diversionist
  mindRoles:
  - MindRoleDiversionist
  blacklist:
    components:
    - AntagImmune
