using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Vanilla.DiscordAuth;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private DiscordAuthManager _discordAuthManager = default!;

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += (_) =>
        {
            _discordAuthManager.SkipAuth();
        };

        UrlEdit.Text = _discordAuthManager.AuthUrl;
        OpenUrlButton.OnPressed += (_) =>
        {
            if (_discordAuthManager.AuthUrl != string.Empty)
            {
                IoCManager.Resolve<IUriOpener>().OpenUri(_discordAuthManager.AuthUrl);
            }
        };
        SkipAuthButton.OnPressed += (_) =>
        {
            _discordAuthManager.SkipAuth();
        };
    }

}
