using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Background;

[GenerateTypedNameReferences]
public sealed partial class BackgroundControl : Control
{
    private readonly bool _notallowed;
    public Action? OnPressed;
    public BackgroundControl(
        string name,
        string description,
        List<string>? specialDesc,
        bool notallowed,
        bool sponsorOnly)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var backgroundNameMessage = new FormattedMessage();
        var backgroundDescMessage = new FormattedMessage();
        backgroundNameMessage.AddMarkupOrThrow($"[head=2][bold][italic]{Loc.GetString(name)}[/italic][/bold][/head]");
        backgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(backgroundNameMessage);
        DescriptionLabel.SetMessage(backgroundDescMessage);
        _notallowed = notallowed;

        //Особое
        if (specialDesc != null && specialDesc.Count > 0)
        {
            var specialMsg = new FormattedMessage();
            specialMsg.AddMarkupOrThrow(Loc.GetString("background-ui-specials-header"));
            specialMsg.PushNewline();
            foreach (var specialText in specialDesc)
            {
                specialMsg.AddMarkupOrThrow(specialText);
                specialMsg.PushNewline();
            }
            SpecialsLabel.SetMessage(specialMsg);
        }

        Button.OnPressed += _ =>
        {
            OnPressed?.Invoke();
            Button.Disabled = true;
            Button.Text = "Выбрано";
        };

        if (notallowed)
        {
            Button.Text = "Недоступно";
            Button.Disabled = true;
        }

        if (sponsorOnly)
            Line.Color = Color.Gold;
    }

    public void Refreshbtn()
    {
        if (_notallowed)
        {
            Button.Disabled = false;
            Button.Text = "Недоступно";
        }
        else
        {
            Button.Disabled = false;
            Button.Text = "Выбрать";
        }
    }

    public BackgroundControl(string name, string description, bool sponsorOnly)
    {
        _notallowed = true;
        RobustXamlLoader.Load(this);
        var backgroundNameMessage = new FormattedMessage();
        var backgroundDescMessage = new FormattedMessage();
        backgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        backgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(backgroundNameMessage);
        DescriptionLabel.SetMessage(backgroundDescMessage);
        Button.Visible = false;

        if (sponsorOnly)
            Line.Color = Color.Gold;
    }
}
