using Content.Shared.Chemistry.Reagent;
using Content.Client.Vanilla.UserInterface.BrainWorm.Chemicals.Controls;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Vanilla.UserInterface.BrainWorm.Chemicals;

[GenerateTypedNameReferences]
public sealed partial class WormChemicalsWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly Dictionary<ChemicalControl, float> _controls = new();
    public event Action<string>? OnChemicalSelected;

    public WormChemicalsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(Dictionary<string, float> reagents, float currentChemicals, float chemcup)
    {
        ChemicalsContainer.DisposeAllChildren();
        _controls.Clear();
        Chemicals.Text = $"Химикатов: {(int)currentChemicals}/{(int)chemcup}";

        foreach (var (proto, cost) in reagents)
        {
            if (!_prototype.TryIndex<ReagentPrototype>(proto, out var reagent))
                continue;

            var desc = reagent.LocalizedDescription;
            if (desc.Length > 200)
                desc = desc.Substring(0, 200) + "...";

            var name = $"{reagent.LocalizedName} ({cost})";
            var control = new ChemicalControl(name, desc, reagent.SubstanceColor);

            // сразу выставляем доступность
            control.ChemicalButton.Disabled = currentChemicals < cost;

            control.OnPressed += () => OnChemicalSelected?.Invoke(proto);

            ChemicalsContainer.AddChild(control);
            _controls[control] = cost;
        }
    }

    public void UpdateChemicalCount(float chemicals, float chemcup)
    {
        Chemicals.Text = $"Химикатов: {(int)chemicals}/ {(int)chemcup}";

        foreach (var (control, cost) in _controls)
        {
            control.ChemicalButton.Disabled = chemicals < cost;
        }
    }

}
